### PR TITLE
Added syntax diagram

### PR DESCRIPTION
**Pull request by janverhaegen**
Screenshot of new page

### CODE REVIEW

**Comment by michaellperry** [comment]
I think this will be very helpful. I made [one small change](https://github.com/jinaga/jinaga_com/commit/d564728872bf9291ffacbc2dbfe8d936e82dda04) to combine the dot operator with the `then` and `suchThat` methods. This was mostly to fix the confusion around the symbols appearing backwards when the railroad diagram loops back.

There are a couple of ideas that this diagram doesn't capture that I think will be important. It doesn't show the difference between a specification and a template function. And it doesn't show that `.suchThat` can occur more than once.

[`j.for`](http://localhost:8000/documents/reference/jinaga/for/) doesn't actually take a specification. It takes a function that returns a specification. The diagram implies that `j.for(j.match(...))` would be valid syntax. I'd like some indicator here that the developer has to stop and create a template function. I'm not sure how best to illustrate that.

After a `.suchThat`, you can append another `.suchThat`. This has the effect of an "and". I considered naming the function `.and` in this scenario, similar to `.then`. But I decided that I didn't want to imply that you could use `.or`. There are very good reasons not to allow "or"s. When I changed the `?` to a `*`, railroad did some strange things with the parentheses that are correct but confusing.

Also it should be noted that `.suchThat` takes a function, not a condition directly. This is the same issue as with `j.for`, but it also has the side-effect of disambiguating repeated `.suchThat` clauses. If they appear inside of the conditional function, then they apply to the inner condition. If they appear outside, then they apply to the outer condition.

Any ideas on how to make these concepts clearer?

**Comment by janverhaegen** [comment]
Attached 3 possibilities that tell the user that a preposition needs a **function that returns** a specification, and not just a specification.   Suggestions, preferences, other solutions ?

**Comment by michaellperry** [comment]
I think we can rule out C because it could be inferred that the keyword `function` appears right after the parenthesis. Between A and B, I like how B is consistent with the other diagrams. The colored box is always a reference to another diagram.

The looping structure with the `.then` is very easy to understand, especially with the extra arrows.

Let's move forward with B.

**Comment by janverhaegen** [comment]
I guess we are getting closer.  Looking forward to corrections and further suggestions.
Btw, although Jinaga allows nesting of j.not clauses, i omitted nesting intentionally from the "restriction"-diagram as i think it has no real use.  Please correct me if i'm wrong.

**Comment by michaellperry** [comment]
This is so good. Breaking out Restriction solved the backward symbol problem and made it reusable. One minor change: I would probably call it a Predicate.

You are correct. Nesting `not` is possible, but not useful. I think I even have a test demonstrating that it does what you expect. But it would be silly to use in practice.

**Comment by michaellperry** [comment]
This is fantastic! I think I have a fix for the Netlify build. I'm going to merge it and try it out.

**Comment by michaellperry** [comment]
There it is! https://jinaga.com/documents/reference/syntax-diagram/

**Pull request merged**
